/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wholezero_passify_Keccak1600_KeccakSponge */

#ifndef _Included_org_wholezero_passify_Keccak1600_KeccakSponge
#define _Included_org_wholezero_passify_Keccak1600_KeccakSponge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wholezero_passify_Keccak1600_KeccakSponge
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wholezero_passify_Keccak1600_00024KeccakSponge_init
  (JNIEnv *, jobject);

/*
 * Class:     org_wholezero_passify_Keccak1600_KeccakSponge
 * Method:    absorb
 * Signature: (Lscala/collection/Seq;)V
 */
JNIEXPORT void JNICALL Java_org_wholezero_passify_Keccak1600_00024KeccakSponge_absorb
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_wholezero_passify_Keccak1600_KeccakSponge
 * Method:    squeeze
 * Signature: (Ljava/lang/Integer;)Lscala/collection/Seq;
 */
JNIEXPORT jobject JNICALL Java_org_wholezero_passify_Keccak1600_00024KeccakSponge_squeeze
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
